//FUNZIONE PER IL CONTROLLO DI UNA STRINGA PALINDROMA
function palindromeString (word){
    
    //ANDIAMO A DEFINIRE UNA VARIABILE CHE CONTERRA' LA NOSTRA STRINGA AL CONTRARIO (wordRev)
    let wordRev = ""
    //CREIAMO UNA VARIABILE DI CONTROLLO PER LA NOSTRA FUNZIONE
    let wordCheck = false
    //IMPOSTIAMO UN CICLO INVERSO CHE SI RIPETA TANTE VOLTE QUANTO E' LUNGA LA STRINGA
    for(let i = word.length - 1 ; i >= 0; i-- ){

        //ANDIAMO A COPIARE I CARATTERI DALL'ULTIMO AL PRIMO NELLA NOSTRA VARIABILE wordRev
        wordRev += word[i]

    }
        //CONFRONTIAMO LA STRINGA INSERITA DALL'UTENTE CON LA STRINGA INVERTITA
        if ( word === wordRev){

            //SE SONO UGUALI AVREMO UNA STRINGA PALINDROMA
            return wordCheck = true
        }
        
        //ALTRIMENTI SARANNO DUE STRINGHE DIVERSE
        return wordCheck
       
}


//CHIEDIAMO ALL'USER DI INSERIRE UNA PAROLA E LA SALVIAMO IN UNA VARIABILE
const word = prompt("Inserisci una parola")
//INVOCAZIONE DELLA FUNZIONE E OUTPUT DEL RISULTATO SU CONDIZIONE
if (palindromeString(word)){
    //SE LA FUNZIONE RESTITUISCE TRUE SARA' PALINDROMA
    alert("HAI INSERITO UNA PAROLA PALINDROMA")
    //ALTRIIMENTI LA PAROLA NON E' PALINDROMA
}else{
    alert("LA PAROLA NON E' PALINDROMA")
}
